{{ if .Values.gitea.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ template "tools-backup.fullname" . }}-gitea"
  labels:
    app: {{ template "tools-backup.name" . }}
    chart: {{ template "tools-backup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.gitea.schedule }}"
  concurrencyPolicy: Forbid   # https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: {{ .Values.image.kubectl.repository }}:{{ .Values.image.kubectl.tag }}
            imagePullPolicy: {{ .Values.image.kubectl.pullPolicy }}
            command: ["/bin/sh"]
            args: ["/app/scripts/backup-gitea.sh"]
            resources:
{{ toYaml .Values.resources | indent 14 }}
            volumeMounts:
            - mountPath: /tmp
              name: backup-dir
            - mountPath: /app/scripts
              name: backup-scripts
{{- if .Values.jenkins.serviceAccountSecretName }}
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: service-account-secret-name
              readOnly: true
{{ end }}
          - name: s3
            image: {{ .Values.image.s3.repository }}:{{ .Values.image.s3.tag }}
            imagePullPolicy: {{ .Values.image.s3.pullPolicy }}
            command: ["/bin/sh"]
            args: ["/app/scripts/upload-to-s3.sh"]
            resources:
{{ toYaml .Values.resources | indent 14 }}
            volumeMounts:
            - mountPath: /tmp
              name: backup-dir
            - mountPath: /app/scripts
              name: backup-scripts
          #securityContext:
          #  runAsUser: 0
          serviceAccount: {{ .Values.gitea.serviceAccount }}
          serviceAccountName: {{ .Values.gitea.serviceAccount }}
          volumes:
          - name: backup-dir
            emptyDir: {}
          - name: backup-scripts
            configMap:
              defaultMode: 0755
              name: "{{ template "tools-backup.fullname" . }}-script"
{{- if .Values.jenkins.serviceAccountSecretName }}
          - name: service-account-secret-name
            secret:
              defaultMode: 0644
              secretName: {{ .Values.gitea.serviceAccountSecretName }}
{{ end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
        {{- end }}
          restartPolicy: OnFailure
{{ end }}